### ISSUE TITLE
Pump speed control

### ISSUE THREAD

**Issue by samuelshng** [jaksi/leviathan#2]
From what I can see, seems like the speed setting only affects the fan, not the pump. Will you consider implementing pump speed control in the future? Thanks!

**Comment by robfrawley** [comment]
The "speed" CLI option sets __both fan and pump speed__. This can be confirmed by looking at the [cooler.py](https://github.com/jaksi/leviathan/blob/master/leviathan/cooler.py) source, specifically [cooler.py#L82](https://github.com/jaksi/leviathan/blob/master/leviathan/cooler.py#L82) and [cooler.py#L88](https://github.com/jaksi/leviathan/blob/master/leviathan/cooler.py#L88). You cannot currently define the speeds _separately_, but you can absolutely set the pump speed, it's just locked to the fan speed ATM.

**Comment by samuelshng** [comment]
Thanks!

It'd be great if they can be decoupled, and if the pump speed can go lower than 30%. I recall seeing the pump speed going down to the ~2400-2600 RPM ballpark when controlling the Kraken X61 through CAM on Windows. Using levctl, at a speed of 30% the pump is at 3000 RPM. 

Great work nonetheless, leviathan has saved me from having to install a Windows partition just to configure the Kraken :).

**Comment by jaksi** [comment]
>From what I can see, seems like the speed setting only affects the fan, not the pump. Will you consider implementing pump speed control in the future?

I also noticed that the pump speed is sometimes really slow to respond, but I couldn't figure out the reason. From the hardware's perspective, the only difference between leviathan and CAM is that CAM is always running and communicating, while leviathan only sends the required commands to change the parameters a single time. This might be the reason, I'm not sure.

>It'd be great if they can be decoupled

Judging by the protocol, it should be possible to control the pump and fan speeds separately, but doing that resulted an even less responsive communication between leviathan and the hardware, that's why I didn't end up implementing it.

>and if the pump speed can go lower than 30%.

As for the speed limit, the last version of CAM I've used sent the same speeds for the 25% and 30% settings, so you couldn't actually set a 25% speed. This might have changed, since a new major version of CAM has come out since, AFAIK.

Also, all of this stuff is described in [PROTOCOL.md](https://github.com/jaksi/leviathan/blob/master/PROTOCOL.md).

>Great work nonetheless, leviathan has saved me from having to install a Windows partition just to configure the Kraken :).

Thanks for the feedback, it means a lot.
